name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: IP
      run: ifconfig
    # - name: executing remote ssh commands using ssh key
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY_SERVER }}
    #     port: ${{ secrets.PORT }}
    #     script: echo 'helloworld' > hellofile.txt